// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ShopCouponallColumns holds the columns for the "shop_couponall" table.
	ShopCouponallColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "active", Type: field.TypeBool},
	}
	// ShopCouponallTable holds the schema information for the "shop_couponall" table.
	ShopCouponallTable = &schema.Table{
		Name:       "shop_couponall",
		Columns:    ShopCouponallColumns,
		PrimaryKey: []*schema.Column{ShopCouponallColumns[0]},
	}
	// ProductProductColumns holds the columns for the "product_product" table.
	ProductProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "clayful_id", Type: field.TypeString, Default: ""},
		{Name: "clayful_options", Type: field.TypeJSON, Nullable: true},
	}
	// ProductProductTable holds the schema information for the "product_product" table.
	ProductProductTable = &schema.Table{
		Name:       "product_product",
		Columns:    ProductProductColumns,
		PrimaryKey: []*schema.Column{ProductProductColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ShopCouponallTable,
		ProductProductTable,
		UsersTable,
	}
)

func init() {
	ShopCouponallTable.Annotation = &entsql.Annotation{
		Table: "shop_couponall",
	}
	ProductProductTable.Annotation = &entsql.Annotation{
		Table: "product_product",
	}
}
