// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductProductColumns holds the columns for the "product_product" table.
	ProductProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "clayful_id", Type: field.TypeString, Default: ""},
		{Name: "clayful_options", Type: field.TypeJSON, Nullable: true},
	}
	// ProductProductTable holds the schema information for the "product_product" table.
	ProductProductTable = &schema.Table{
		Name:       "product_product",
		Columns:    ProductProductColumns,
		PrimaryKey: []*schema.Column{ProductProductColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductProductTable,
		UsersTable,
	}
)

func init() {
	ProductProductTable.Annotation = &entsql.Annotation{
		Table: "product_product",
	}
}
